CREATE TABLE PLAYER_ACCOUNT
(
	AccountID BIGINT CONSTRAINT FK_PLAYER_ACCOUNT_PLAYERID FOREIGN KEY REFERENCES PLAYER(ID) ON DELETE CASCADE,
	Date_Opened DATE NOT NULL,
	Balance INT NOT NULL
)

ALTER TABLE PLAYER_ACCOUNT ADD CONSTRAINT SET_ZERO DEFAULT 0 FOR Balance;