CREATE TABLE PLAYER
(
	ID BIGINT CONSTRAINT PK_PLAYER_ID PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	DateOfBirth DATE NOT NULL
)

IF EXISTS(
  SELECT *
    FROM sys.triggers
   WHERE name = N'new_account'
     AND parent_class_desc = N'OBJECT_OR_COLUMN'
)
	DROP TRIGGER gi203242.new_account
GO

CREATE TRIGGER gi203242.new_account 
   ON  gi203242.PLAYER
   AFTER INSERT
AS 
BEGIN
	INSERT INTO PLAYER_ACCOUNT (AccountID, Date_Opened)
	SELECT ID, GETDATE() FROM INSERTED
END
GO